package alert_Windows_4;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class SwitchCommand {

	
//	1) Launch new Browser
//	2) Open URL “http://www.toolsqa.com/automation-practice-switch-windows/”
//	3) Click on Button “Alert Box”, it will open a Pop Up Window generated by JavaScript
//	4) Switch to Alert window (Use ‘SwitchTo()Alert() command)
//	5) Close the Pop Up Window (Use Accept command)
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		// Create a new instance of the Firefox driver
        WebDriver driver = new FirefoxDriver();

        // Put an Implicit wait, this means that any search for elements on the page could take the time the implicit wait is set for before throwing exception
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        // Launch the URL
        driver.get("http://www.toolsqa.com/automation-practice-switch-windows/");

        // Click on the Button "Alert Box"
        driver.findElement(By.name("Alert Box")).click();

        // Switch to JavaScript Alert window
        Alert myAlert = driver.switchTo().alert();
        

        // Accept the Alert
        myAlert.accept();

        // Close Original window
        driver.close();
        
	}

}
